### ISSUE TITLE
Pull in translations from Transifex

### ISSUE THREAD

**Issue by 1ec5** [Project-OSRM/osrm-text-instructions.swift#10]
This library should pull translations directly from Transifex and convert them into plist format to complement the existing English plist. This should be done as a build step to keep developers from having to access the Transifex API every time they run `carthage bootstrap`.

/cc @frederoni @freenerd

**Comment by freenerd** [comment]
Given that we would not walk lock-step with osrm-text-instructions anymore, this would break the [integration tests](https://github.com/Project-OSRM/osrm-text-instructions.swift/blob/master/OSRMTextInstructionsTests/OSRMTextInstructionsTests.swift) (which are built by the javascript [osrm-text-instructions](https://github.com/Project-OSRM/osrm-text-instructions)).

**Comment by 1ec5** [comment]
Another option is to pull in osrm-text-instructions as a submodule, but we’ll want to make sure that affects only our development process and doesn’t have any impact post-build (like when a developer integrates the framework). Either way, we’ll need to coordinate PRs that update translations between both repositories. (I’d like to avoid maintaining a separate suite of integration tests here if possible.)
