### ISSUE TITLE
CocoaPods install does not include Instructions.plist

### ISSUE THREAD

**Issue by joneswah** [Project-OSRM/osrm-text-instructions.swift#12]
If you install using cocoa pods.

> pod 'OSRMTextInstructions', :git => 'https://github.com/Project-OSRM/osrm-text-instructions.swift.git'

The Instructions.plist is not included and then you get a crash on the line.

`let OSRMTextInstructionsStrings = NSDictionary(contentsOfFile: Bundle(for: OSRMInstructionFormatter.self).path(forResource: "Instructions", ofType: "plist")!)!`

The temporary work around is to manually add the Instructions.plist to the pod folder manually. (which is obviously not a viable long term option)

I suspect it got introduced when you moved the plist files into localised folders so the s.resources no longer matches.

> s.resources = ['OSRMTextInstructions/*.plist']

**Comment by 1ec5** [comment]
Good cath, and sorry for the inconvenience. #13 will fix this issue.
