### ISSUE TITLE
Incompatibility with `MapboxDirections` and `MapboxCoreNavigation`

### ISSUE THREAD

**Issue by Augustyniak** [Project-OSRM/osrm-text-instructions.swift#55]
I ran into a problem when I tried to use `MapboxDirections`, `OSRMTextInstructions` and `MapboxCoreNavigation` pods in one project.

The problem is caused by the fact that that there are API changes between `MapboxDirections 0.13`  and `Mapbox Directions 0.16`  which aren't backward compatible (despite the fact that according to [semantic versioning](https://semver.org) 0.16 should be backward compatible with 0.13).

Any chance that you can release a new version of `osrm text instructions` that works with the newest release of `MapboxDirections` (`0.16`)?

Podfile
```
target 'Example' do
  use_frameworks!

  pod 'MapboxDirections.swift'
  pod 'OSRMTextInstructions'
  pod 'MapboxCoreNavigation' 
end
```

Podfile.lock
```
PODS:
  - MapboxCoreNavigation (0.13.0):
    - MapboxDirections.swift (~> 0.16.0)
    - MapboxMobileEvents (~> 0.2)
    - Turf (~> 0.0.4)
  - MapboxDirections.swift (0.16.0):
    - Polyline (~> 4.2)
  - MapboxMobileEvents (0.2.10)
  - OSRMTextInstructions (0.6.0):
    - MapboxDirections.swift (~> 0.13)
  - Polyline (4.2.0)
  - Turf (0.0.4)

DEPENDENCIES:
  - MapboxCoreNavigation
  - MapboxDirections.swift
  - OSRMTextInstructions

SPEC CHECKSUMS:
  MapboxCoreNavigation: 3c964ad1854179dc619b4cceb5f85f428b68fe14
  MapboxDirections.swift: 168cc83745b188d792c5482bfb0653c233d1455c
  MapboxMobileEvents: 9e48b59d0eed04508595dcb04a77b7632e1c3054
  OSRMTextInstructions: 7abc90eaf50ff1f7333c526daf360f6a2f1ea059
  Polyline: 3d69f75bb136357e27291d439d0436c6ebda57a4
  Turf: 6c169618fa671e3f8a7b764b5b3332053ad6110e

PODFILE CHECKSUM: 2451d9656bb36e932469bfba9f5797a86fca4499

COCOAPODS: 1.4.0
```

**Comment by 1ec5** [comment]
> despite the fact that according to [semantic versioning](https://semver.org) 0.16 should be backward compatible with 0.13

This library [hasn’t reached v1.0 yet](https://semver.org/#spec-item-4), so a breaking change can occur at any time. In practice, we try to only make breaking changes in minor versions in our pre-1.0 Swift libraries, so you can pin to a patch release to avoid surprises.
